// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DYdbctURj6znriEVDx10zMA-Gf51RxU',
    appId: '1:100763050650:web:f661c83a68dcd557977523',
    messagingSenderId: '100763050650',
    projectId: 'pqc-chat',
    authDomain: 'pqc-chat.firebaseapp.com',
    storageBucket: 'pqc-chat.firebasestorage.app',
    measurementId: 'G-EK6W0D3FBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXH1yyVkfYa3xdbM65NNRVdxS4zgBN78',
    appId: '1:100763050650:android:e9bd7a954b087363977523',
    messagingSenderId: '100763050650',
    projectId: 'pqc-chat',
    storageBucket: 'pqc-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdLOYJEkuC7M0cd8CnsgMky-1EBOfxis',
    appId: '1:100763050650:ios:3b6ae897287f760a977523',
    messagingSenderId: '100763050650',
    projectId: 'pqc-chat',
    storageBucket: 'pqc-chat.firebasestorage.app',
    iosBundleId: 'com.example.chatinng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdLOYJEkuC7M0cd8CnsgMky-1EBOfxis',
    appId: '1:100763050650:ios:3b6ae897287f760a977523',
    messagingSenderId: '100763050650',
    projectId: 'pqc-chat',
    storageBucket: 'pqc-chat.firebasestorage.app',
    iosBundleId: 'com.example.chatinng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DYdbctURj6znriEVDx10zMA-Gf51RxU',
    appId: '1:100763050650:web:e0427294596845e0977523',
    messagingSenderId: '100763050650',
    projectId: 'pqc-chat',
    authDomain: 'pqc-chat.firebaseapp.com',
    storageBucket: 'pqc-chat.firebasestorage.app',
    measurementId: 'G-XJ2MKPX180',
  );
}
